### ISSUE TITLE
Installation Error `FileNotFoundError: [Errno 2] No such file or directory: '.../nbextension'`

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-multi_outputs#27]
The following error occurred while installation

```
$ jupyter nbextension install --py lc_multi_outputs --user
Installing /Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/lc_multi_outputs/nbextension -> multi_outputs
Copying: /Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/lc_multi_outputs/nbextension -> /Users/yazawasatoshi/Library/Jupyter/nbextensions/multi_outputs
Traceback (most recent call last):
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 199, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 1046, in _maybe_copy
    shutil.copy2(src, dest)
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yazawasatoshi/workspace/nii-cloud/miniconda3/lib/python3.6/site-packages/lc_multi_outputs/nbextension'
```

It seems that MANIFEST.in is missing?

**Comment by yacchin1205** [comment]
@shingo78  Could you check it?
